### ISSUE TITLE
Difference in "heat capacity rate ratio" and "heat capacity ratio" 

### ISSUE THREAD

**Issue by max3-2** [CalebBell/ht#10]
Hi, 

as the title says, both the terms *heat capacity rate ratio* and *heat capacity ratio*  seem to be used in the documentation. Can someone elaborate on if there is a difference or both is the ratio of (m * cp)? I feel like publications are also not always clear.

On a connected sidenote, sometimes this is specified with *...with respect to stream 1* - does this mean that stream `1`  is in the denominator?

**Comment by CalebBell** [comment]
Hi Max,

I think my documentation may have confused you via a typo in the units of the "Cr heat capacity rate ratio," where I specified units of W/K instead of dimensionless. I have corrected the definition.

To clarify, **heat capacity ratio** (commonly represented as $C_r$) refers to the ratio of the heat capacities of two fluids in a heat exchanger, given as:

$$
C_r = \frac{C_{\text{min}}}{C_{\text{max}}}
$$

This ratio is dimensionless because it is simply a comparison between the heat capacities of the two streams (the smaller fluid to the larger one). 

The **heat capacity rate** is $m \cdot C_p$ (mass flow rate times the specific heat capacity), and here expressed in units of W/K which is also (J/(s·K)). The **heat capacity rate ratio** is the dimensionless ratio of the heat capacity rates of the two fluids $C_r$.

Regarding your question about "with respect to stream 1," yes with respect means stream 1 is the denominator.

Sincerely,
Caleb
